config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    authenticate :user, ->(user) { user.is_admin? } do
      mount Sidekiq::Web, at: 'sidekiq'
      mount PgHero::Engine, at: 'pghero'
    end
  end

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'job_leads#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :assistant_configurations, except: %i[show create]
  resources :gmail_integrations, controller: 'assistant_configurations'

  resources :job_sources do
    resources :job_leads, except: %i[index show]
  end
  resources :job_leads, only: %i[index show]
  resources :notifiers, except: %i[index show] do
    member do
      patch :refresh_telegram_token
    end
  end
  resources :notes, only: %i[new create destroy]
  resources :gmail_messages, only: %i[index show]

  namespace :telegram, defaults: { format: :json } do
    post :message
  end
  namespace :google_oauth2 do
    namespace :gmail do
      get :auth
      get :callback
    end
  end
end

Rails.application.routes.default_url_options[:host] = Rails.application.credentials.host

app/models/notifier.rb
# == Schema Information
#
# Table name: notifiers
#
#  id              :bigint           not null, primary key
#  name            :string           not null
#  kind            :integer          default("slack_webhook")
#  owner_type      :string           not null
#  owner_id        :bigint           not null
#  user_id         :bigint           not null
#  settings        :jsonb
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  deleted_at      :datetime
#  sanitized_links :boolean          default(FALSE), not null
#
class Notifier < ApplicationRecord
  include Notifier::Telegram

  KINDS = %i[
    slack_webhook
    email
    telegram
  ].freeze

  SETTINGS_FIELDS = {
    slack_webhook: %i[webhook_url],
    email: %i[email_address],
    telegram: %i[telegram_username telegram_chat_id telegram_start_token]
  }.freeze

  def self.all_settings_fields
    SETTINGS_FIELDS.values.flatten.uniq
  end

  store_accessor :settings, all_settings_fields
  enum :kind, KINDS, suffix: true, default: :slack_webhook

  belongs_to :owner, polymorphic: true
  belongs_to :user

  after_initialize do
    self.name ||= "My new #{kind&.humanize} Notifier" if new_record?
  end

  validates :kind, :name, presence: true
  validate :kind_not_changed, if: -> { persisted? && will_save_change_to_kind? }
  validates_uniqueness_of_without_deleted :name, scope: :owner_id

  def settings_fields
    SETTINGS_FIELDS[kind.to_sym].uniq
  end

  private

  def kind_not_changed
    errors.add(:kind, 'Change of kind not allowed!')
  end
end

app/models/notifier/telegram.rb
class Notifier
  module Telegram
    include ActionView::RecordIdentifier

    extend ActiveSupport::Concern
    included do
      attr_accessor :skip_telegram_fields_validation

      validate :telegram_fields_presence, if: -> { telegram_kind? }
      validate :telegram_fields_not_changed, if: lambda {
        persisted? && telegram_kind? && !skip_telegram_fields_validation
      }

      before_create :telegram_username_formatted, if: -> { telegram_kind? }
      after_create :generate_telegram_start_token

      def telegram_bot_link
        telegram_link = "https://t.me/#{Rails.application.credentials.telegram.bot.name}"
        telegram_link += "?start=#{telegram_start_token}" if telegram_start_token.present?
        telegram_link
      end

      def generate_telegram_start_token
        return unless telegram_kind? && owner_id.present? && owner_type.present?

        self.skip_telegram_fields_validation = true
        self.telegram_chat_id = nil
        self.telegram_start_token = TelegramBot::StartToken.generate_token(self, expires_in: 1.hour)
        save
      end

      def telegram_bot_start!(telegram_bot_chat_id_value)
        return unless telegram_kind? && telegram_chat_id.blank?

        self.skip_telegram_fields_validation = true
        self.telegram_chat_id = telegram_bot_chat_id_value
        self.telegram_start_token = nil
        save

        broadcast_replace_to(
          :notifiers,
          target: "#{dom_id(self)}_telegram_bot_link",
          partial: 'notifiers/telegram_bot_link',
          locals: { notifier: self }
        )
      end
    end

    private

    def telegram_fields_presence
      errors.add(:telegram_username, 'should be present!') if send(:telegram_username).blank?
    end

    def telegram_fields_not_changed
      errors.add(:settings_field, 'changes not allowed!') if will_save_change_to_settings?
    end

    def telegram_username_formatted
      self.telegram_username = telegram_username.sub(/^@/, '')
    end
  end
end

app/controllers/notifiers_controller.rb
class NotifiersController < ApplicationController
  before_action :set_owner_from_params, only: %i[new create update]
  before_action :set_notifier, only: %i[edit update destroy refresh_telegram_token]

  def new
    @notifier = current_user.notifiers.build(notifier_params)
  end

  def edit
    @owner = @notifier.owner
  end

  def create
    @notifier = current_user.notifiers.build(notifier_params)
    if @notifier.save
      respond_to do |format|
        path = @notifier.telegram_kind? ? edit_notifier_path(@notifier) : edit_polymorphic_path(@owner)
        format.html { redirect_to path, notice: t('.notice') }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @notifier.update(notifier_params)
      respond_to do |format|
        format.html { redirect_to edit_polymorphic_path(@owner), notice: t('.notice') }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @notifier.destroy

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = t('.notice') }
    end
  end

  def refresh_telegram_token
    @notifier.generate_telegram_start_token

    # render status: :ok
    respond_to do |format|
      format.html { redirect_to edit_notifier_path(@notifier), notice: t('.notice') }
      format.turbo_stream { flash.now[:notice] = t('.notice') }
    end
  end

  private

  def set_notifier
    @notifier = current_user.notifiers.find(params[:id])
  end

  def set_owner_from_params
    @owner = notifier_params[:owner_type].constantize.find_by(id: notifier_params[:owner_id], user_id: current_user.id)
  end

  def notifier_params
    params.fetch(:notifier, {}).permit(
      :owner_id,
      :owner_type,
      :name,
      :kind,
      :sanitized_links,
      settings: Notifier.all_settings_fields
    )
  end
end

app/views/notifiers/_form.html.erb
<%= simple_form_for notifier do |f| %>
  <%= form_server_error_notification(notifier) %>

  <%= f.input :owner_type, as: :hidden, input_html: { value: owner.class.name } %>
  <%= f.input :owner_id, as: :hidden, input_html: { value: owner.id } %>

  <%= turbo_frame_tag f.field_id(:kind, :turbo_frame) do %>
    <div class="form__row">
      <div data-controller="search-params element">
        <%= f.input :kind,
                    input_html: {
                      "disabled" => notifier.persisted?,
                      "data-action" => "change->search-params#encode change->element#click"
                    },
                    collection: Notifier.kinds.keys,
                    selected: notifier.kind %>

        <a href="<%= new_notifier_path(notifier: { owner_type: owner.class.name, owner_id: owner.id }) %>"
          data-search-params-target="anchor"
          data-element-target="click"
          data-turbo-frame="<%= f.field_id(:kind, :turbo_frame) %>"
          hidden></a>
      </div>

      <%= f.input :name %>
      <%= f.input :sanitized_links, wrapper_html: { class: 'form__group-checkbox' } %>
    </div>

    <div class="form__row">
      <%= render partial: 'form_settings', locals: { form: f, notifier: notifier } %>
    </div>

    <div class="form__actions">
      <%= link_to "Cancel", edit_polymorphic_path(owner), class: "btn btn--light", data: { turbo_frame: "_top" } %>
      <%= f.submit class: "btn btn--secondary", data: { turbo_frame: "_top" } %>
    </div>
  <% end %>
<% end %>

app/views/notifiers/_form_settings.html.erb
<% if notifier.telegram_kind? %>
  <%= render partial: 'form_telegram_settings', locals: { form: form, notifier: notifier } %>
<% else %>
  <%= form.simple_fields_for :settings do |s| %>
    <% notifier.settings_fields.each do |field_name| %>
      <%= s.input field_name,
          placeholder: settings_field_placeholder(field_name),
          label: false,
          input_html: { value: notifier.send(field_name) } %>
    <% end %>
  <% end %>
<% end %>

app/views/notifiers/_form_telegram_settings.html.erb
<div style="width: 100%; text-align: center;">
  <% if notifier.persisted? %>
    <%= turbo_stream_from :notifiers %>
    <%= turbo_frame_tag "#{dom_id(notifier)}_telegram_bot_link" do %>
      <%= render partial: "telegram_bot_link", locals: { notifier: notifier } %>
    <% end %>
  <% else %>
    <%= form.simple_fields_for :settings do |s| %>
      <%= s.input :telegram_username,
          placeholder: "@username",
          label: false %>
    <% end %>
  <% end %>
</div>

app/views/notifiers/_notifier.html.erb
<%= turbo_frame_tag notifier do %>
  <div class="notifier">
    <b><%= notifier.name.truncate(45, separator: /\s/, ommission: "....") %></b>
    <div class="notifier__actions">         
      <%= link_to edit_notifier_path(notifier), data: { turbo_frame: "_top" }, class: "btn btn--light" do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
      <%= confirmation_link_to notifier_path(notifier), class: "btn btn--light", data: { turbo_method: :delete } do %>
        <i class="fa-solid fa-trash-can"></i>             
      <% end %>
    </div>
  </div>
<% end %> 

app/views/notifiers/_telegram_bot_link.html.erb
<% if notifier.telegram_chat_id.present?  %>
  <b>You have connected</b>
  <%= link_to notifier.telegram_bot_link, target: '_blank' do %>
    @<%= Rails.application.credentials.telegram.bot.name %>
  <% end %>
  <b>to @<%= notifier.telegram_username %></b>
<% else %>
  For connect the Telegram Notifier Bot please click on <%= link_to "@#{Rails.application.credentials.telegram.bot.name}", notifier.telegram_bot_link, target: '_blank' %>
  <div class="form__group-copy-to-clipboard" data-controller="copy-to-clipboard">  
    Or copy and open the link on your device
    <input class="form__input" type="text" data-copy-to-clipboard-target="text" value="<%= notifier.telegram_bot_link %>">
    <div class="btn btn--copy-to-clipboard btn--compact prevent-select" data-action="click->copy-to-clipboard#copy">
      <i class="fa-solid fa-copy fa-xl"></i>
      <span>copy</span>
    </div>
    <%= confirmation_link_to refresh_telegram_token_notifier_path(notifier),
                             class: "btn btn--refresh btn--compact",
                             data: { turbo_method: :patch, message: "Are you sure about refresh Telegram Bot connection link?" } do %>
      <i class="fa-solid fa-arrows-rotate fa-xl"></i>
      <span>refresh</span>
    <% end %> 
  </div>
  <i>*the link expires in 1 hour</i>
<% end %>

app/views/notifiers/destroy.turbo_stream.erb
<%= turbo_stream.remove @notifier %>
<%= render_turbo_stream_flash_messages %>

app/views/notifiers/edit.html.erb
<%= link_to sanitize("&larr; Back to #{@owner.model_name.human}"), edit_polymorphic_path(@owner) %>

<div class="header">
  <h2>Edit Notifier</h2>
</div>

<%= turbo_frame_tag @notifier do %>
  <%= render "form", owner: @owner, notifier: @notifier %>
<% end %>  

app/views/notifiers/index.html.erb
<% if @notifiers.blank? %>
  <div class="empty-state">
    <p class="empty-state__text">
      You don't have any notifiers yet!
    </p>
  </div>
<% else %>
  <%= turbo_frame_tag "notifiers" do %>
    <%= render @notifiers %>
  <% end %>
<% end %>

app/views/notifiers/new.html.erb
<%= link_to sanitize("&larr; Back to #{@owner.model_name.human}"), edit_polymorphic_path(@owner) %>

<div class="header">
  <h2>New Notifier</h2>
</div>

<%= turbo_frame_tag @notifier do %>
  <%= render "form", owner: @owner, notifier: @notifier %>
<% end %>

app/views/notifiers/refresh_telegram_token.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>

<%= turbo_stream.update "#{dom_id(@notifier)}_telegram_bot_link" do %>
  <%= render partial: "telegram_bot_link", locals: { notifier: @notifier } %>
<% end %>