config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    authenticate :user, ->(user) { user.is_admin? } do
      mount Sidekiq::Web, at: 'sidekiq'
      mount PgHero::Engine, at: 'pghero'
    end
  end

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'job_leads#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :assistant_configurations, except: %i[show create]
  resources :gmail_integrations, controller: 'assistant_configurations'

  resources :job_sources do
    resources :job_leads, except: %i[index show]
  end
  resources :job_leads, only: %i[index show]
  resources :notifiers, except: %i[index show] do
    member do
      patch :refresh_telegram_token
    end
  end
  resources :notes, only: %i[new create destroy]
  resources :gmail_messages, only: %i[index show]

  namespace :telegram, defaults: { format: :json } do
    post :message
  end
  namespace :google_oauth2 do
    namespace :gmail do
      get :auth
      get :callback
    end
  end
end

Rails.application.routes.default_url_options[:host] = Rails.application.credentials.host

app/models/assistant_configuration.rb
# == Schema Information
#
# Table name: assistant_configurations
#
#  id                :bigint           not null, primary key
#  type              :string           not null
#  settings          :jsonb
#  user_id           :bigint           not null
#  deleted_at        :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  background_job_id :string
#
class AssistantConfiguration < ApplicationRecord
  belongs_to :user
  has_many :notifiers, lambda { |ac|
    unscope(:where).where(owner_type: ac.model_name.name, owner_id: ac.id, deleted_at: nil)
  }, class_name: 'Notifier', inverse_of: :owner, dependent: :destroy # due to STI we have to use notifiers(polymorphic relation) in this odd way

  class << self
    def settings_fields
      { associated_resource_linked_to_navbar: { type: 'boolean', editable: true, visible: true } }.freeze
    end

    def visible_settings_fields
      settings_fields.select { |_k, v| v[:visible] }
    end

    def editable_settings_fields
      settings_fields.select { |_k, v| v[:editable] }
    end
  end

  store_accessor :settings, settings_fields.keys

  scope :linked_to_navbar, -> { where("settings ->> 'associated_resource_linked_to_navbar' = 'true'") }

  validates_uniqueness_of_without_deleted :type, scope: :user_id

  def name
    model_name.human
  end

  def notifiable?
    false
  end

  def associated_resource
    # implement at child STI models depends of your needs
  end
end

app/models/assistant_configuration/gmail_integration.rb
# == Schema Information
#
# Table name: assistant_configurations
#
#  id                :bigint           not null, primary key
#  type              :string           not null
#  settings          :jsonb
#  user_id           :bigint           not null
#  deleted_at        :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  background_job_id :string
#
class GmailIntegration < AssistantConfiguration
  REFRESH_RATE_IN_SECONDS = 360

  has_many :gmail_messages, foreign_key: :assistant_configuration_id, inverse_of: :gmail_integration, dependent: :destroy

  def self.settings_fields
    {
      api_refresh_token: { type: 'string', editable: false, visible: false },
      gmail_user_email: { type: 'string', editable: false, visible: true }
    }.merge(super).freeze
  end

  store_accessor :settings, settings_fields.keys

  after_update :background_processing, if: -> { saved_change_to_settings? && api_refresh_token.present? }
  before_destroy :cancel_background_job

  def notifiable?
    true
  end

  def associated_resource
    GmailMessage
  end

  def background_processing
    cancel_background_job

    bg_job = SyncGmailMessagesJob.set(wait: REFRESH_RATE_IN_SECONDS.seconds).perform_later(id)
    bg_job && update(background_job_id: bg_job.provider_job_id)
  end

  private

  def cancel_background_job
    # TODO: add more logic when background_job is running
    return if background_job_id.blank?

    Sidekiq::Status.unschedule(background_job_id)
  end
end

app/models/assistant_configuration/gmail_settings.rb
# == Schema Information
#
# Table name: assistant_configurations
#
#  id         :bigint           not null, primary key
#  type       :string           not null
#  settings   :jsonb
#  user_id    :bigint           not null
#  deleted_at :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class GmailSettings < AssistantConfiguration
  include Notifier::Telegram

  SETTINGS_FIELDS = %i[refresh_rate].freeze

  store_accessor :settings, SETTINGS_FIELDS
end

app/controllers/assistant_configurations_controller.rb
class AssistantConfigurationsController < ApplicationController
  before_action :set_assistant_configuration, only: %i[edit update destroy]

  def index
    @assistant_configurations = AssistantConfigurations::List.run(current_user)
  end

  def new
    @assistant_configuration = current_user.assistant_configurations.build(type: params[:assistant_configuration][:type])
    render "assistant_configurations/new/#{@assistant_configuration.class.name.underscore}"
  end

  def edit
    render "assistant_configurations/edit/#{@assistant_configuration.class.name.underscore}"
  end

  def update
    permitted_params_of_settings.each { |k, v| @assistant_configuration.send("#{k}=", v) }
    if @assistant_configuration.save
      respond_to do |format|
        format.html { redirect_to assistant_configurations_path, notice: t('.notice') }
        format.turbo_stream { flash.now[:notice] = t('.notice') }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @assistant_configuration.destroy

    respond_to do |format|
      format.html { redirect_to assistant_configurations_path, notice: t('.notice') }
      format.turbo_stream { flash.now[:notice] = t('.notice') }
    end
  end

  private

  def set_assistant_configuration
    @assistant_configuration = current_user.assistant_configurations.find(params[:id])
  end

  def permitted_params_of_settings
    params
      .fetch(:assistant_configuration, {})
      .fetch(:settings, {})
      .permit(
        @assistant_configuration.class.editable_settings_fields.keys
      )
  end
end

app/views/assistant_configurations/_configuration.html.erb
<b><%= configuration.name %></b>
<div class="assistant-settings__configurations-item-actions">
  <%= link_to edit_assistant_configuration_path(configuration), data: { turbo_frame: "_top" }, class: "btn btn--light" do %>
    <i class="fa-solid fa-pen-to-square"></i>
  <% end %>
  <%= confirmation_link_to assistant_configuration_path(configuration), class: "btn btn--light", data: { turbo_method: :delete } do %>
    <i class="fa-solid fa-trash-can"></i>             
  <% end %>
</div>

app/views/assistant_configurations/_configurations.html.erb
<div class="assistant-settings__configurations">
  <% configurations.each do |configuration| %>
    <%= turbo_frame_tag configuration, class: "assistant-settings__configurations-item" do %>
      <% if configuration.persisted? %>
        <%= render partial: "configuration", locals: { configuration: configuration } %>
      <% else %>
        <%= link_to "Configure #{configuration.name}",
                    new_assistant_configuration_path(assistant_configuration: { type: configuration.type }),
                    class: "btn btn--light",
                    data: { turbo_frame: "_top" } %>
      <% end %>
    <% end %>  
  <% end %>
</div>

app/views/assistant_configurations/_form.html.erb
<%= simple_form_for assistant_configuration, as: :assistant_configuration, url: assistant_configuration_path(assistant_configuration) do |f| %>
  <%= form_server_error_notification(assistant_configuration) %>

  <div class="form__row">
    <%= render partial: 'form_settings', locals: { form: f, assistant_configuration: assistant_configuration } %>
  </div>

  <% if assistant_configuration.persisted? && assistant_configuration.notifiable? %>
    <div class="job_source__form-notifiers">
      <div class="job_source__form-notifiers-title">
        <b>Notifiers</b>
        <%= link_to new_notifier_path(notifier: { owner_type: assistant_configuration.class.name, owner_id: assistant_configuration.id }),
                    class: "btn btn--secondary",
                    data: { turbo_frame: "_top" } do %>
          <i class="fas fa-solid fa-plus fa-lg"></i>
        <% end %>            
      </div>

      <%= turbo_frame_tag "notifiers" do %>
        <%= render assistant_configuration.notifiers %>
      <% end %>
    </div>
  <% end %>  

  <div class="form__actions">
    <%= link_to "Cancel", assistant_configurations_path, class: "btn btn--light" %>
    <%= f.submit "Save", class: "btn btn--secondary" %>
  </div>
<% end %>

app/views/assistant_configurations/_form_settings.html.erb
<%= form.simple_fields_for :settings do |s| %>
  <% assistant_configuration.class.visible_settings_fields.each do |field_name, field_settings| %>
    <% field_value = assistant_configuration.send(field_name) %>
    <%= s.input field_name,
        placeholder: (I18n.t!(field_name.to_s, scope: 'simple_form.labels.job_source') rescue settings_field_placeholder(field_name)),
        as: field_settings[:type],
        disabled: !field_settings[:editable],
        checked_value: 'true',
        unchecked_value: 'false',
        input_html: { value: field_value, checked: field_value == 'true' } %>
  <% end %>
<% end %>

app/views/assistant_configurations/destroy.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>

<%= turbo_stream.update @assistant_configuration do %>
  <%= link_to "Configure #{@assistant_configuration.name}",
              new_assistant_configuration_path(assistant_configuration: { type: @assistant_configuration.type }),
              class: "btn btn--light",
              data: { turbo_frame: "_top" } %>
<% end %>

<%= turbo_stream.update "configurations_associated_resources_links" do %>
  <%= links_for_associated_resources_of_configurations %>
<% end %>

app/views/assistant_configurations/index.html.erb
<div class="header">
  <h2>Assistant configuration</h2>
</div>

<div class="assistant-settings">
  <%= render partial: "configurations",  locals: { configurations: @assistant_configurations } %>

  <div class="assistant-settings__bottom">
    <%= link_to job_sources_path, class: "btn btn--light" do %>
      <i class="fas fa-solid fa-rss"></i>
      Job Sources
    <% end %>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn--dark" %>
  </div>
</div>

app/views/assistant_configurations/settings.html.erb
<div class="header">
  <h2>Assistant configuration</h2>
</div>

<div class="assistant-configuration">

  <%= link_to job_sources_path, class: "btn btn--light" do %>
    <i class="fas fa-solid fa-rss"></i>
    Job Sources
  <% end %>

  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn--dark" %>
</div>

app/views/assistant_configurations/update.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>
<%= turbo_stream.update "configurations_associated_resources_links" do %>
  <%= links_for_associated_resources_of_configurations %>
<% end %>