config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    authenticate :user, ->(user) { user.is_admin? } do
      mount Sidekiq::Web, at: 'sidekiq'
      mount PgHero::Engine, at: 'pghero'
    end
  end

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'job_leads#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :assistant_configurations, except: %i[show create]
  resources :gmail_integrations, controller: 'assistant_configurations'

  resources :job_sources do
    resources :job_leads, except: %i[index show]
  end
  resources :job_leads, only: %i[index show]
  resources :notifiers, except: %i[index show] do
    member do
      patch :refresh_telegram_token
    end
  end
  resources :notes, only: %i[new create destroy]
  resources :gmail_messages, only: %i[index show]

  namespace :telegram, defaults: { format: :json } do
    post :message
  end
  namespace :google_oauth2 do
    namespace :gmail do
      get :auth
      get :callback
    end
  end
end

Rails.application.routes.default_url_options[:host] = Rails.application.credentials.host

app/models/job_lead.rb
# == Schema Information
#
# Table name: job_leads
#
#  id            :bigint           not null, primary key
#  title         :string           not null
#  description   :text
#  link          :text             not null
#  potential     :integer          default("medium")
#  status        :integer          default("entry")
#  hourly_rate   :decimal(10, 2)   not null
#  job_source_id :bigint           not null
#  published_at  :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  owner_country :string           default("'US'::character varying"), not null
#  external_id   :string           not null
#  deleted_at    :datetime
#
class JobLead < ApplicationRecord
  include TextFieldsSanitization
  include JobLead::NotifiersProcessing

  enum :status, %i[entry active detached], suffix: true, default: :entry
  enum :potential, %i[low medium high], suffix: true, default: :medium

  belongs_to :job_source
  has_many :notes, as: :owner, dependent: :destroy

  before_validation :generate_external_id, if: -> { !external_id? }

  validates :published_at, :description, :title, :link, :status, :potential, presence: true
  validates :hourly_rate, presence: true, numericality: { greater_than: 0 }
  validates :owner_country, presence: true, inclusion: { in: ISO3166::Country.codes }
  validates_uniqueness_of_without_deleted :external_id, scope: :job_source_id

  delegate :user, to: :job_source
  delegate :notifiers, to: :job_source

  scope :ordered, -> { order(published_at: :desc) }

  broadcasts_to ->(job_lead) { [job_lead.user, 'job_leads'] }, inserts_by: :prepend

  def formatted_title
    title.truncate(70, separator: /\s/, ommission: '....')
  end

  def next_lead_by_status(status_value = nil)
    leads_list = job_source.job_leads.where('published_at > ?', published_at)
    leads_list = leads_list.where(status: status_value) if status_value.present?
    leads_list.ordered.last
  end

  private

  def generate_external_id
    self.external_id = SecureRandom.urlsafe_base64
    generate_external_id if self.class.exists?(external_id:)
  end
end

app/models/job_lead/notifiers_processing.rb
class JobLead
  module NotifiersProcessing
    extend ActiveSupport::Concern

    included do
      after_create :notify
    end

    private

    def notify
      notifiers.each do |notifier|
        NewJobLeadNotificationJob.set(wait: 2.seconds).perform_later(id, notifier.id)
      end
    end
  end
end

app/controllers/job_leads_controller.rb
class JobLeadsController < ApplicationController
  before_action :set_job_source, except: %i[index show]
  before_action :set_job_lead, only: %i[edit update destroy]
  before_action :set_status_filter

  def index
    @job_leads = current_user.job_leads.includes(:job_source).ordered
    verify_sources_present { return }
    return if @status_filter.blank?

    @job_leads = @job_leads.where(status: params[:status_filter])
  end

  def show
    @job_lead = current_user.job_leads.find(params[:id])
    @note = Note.new(owner: @job_lead)
  end

  def new
    @job_lead = @job_source.job_leads.build
  end

  def edit; end

  def create
    @job_lead = @job_source.job_leads.build(job_lead_params)

    if @job_lead.save
      respond_to do |format|
        format.html { redirect_to job_source_path(@job_source), notice: t('.notice') }
        format.turbo_stream { flash.now[:notice] = t('.notice') }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @job_lead.update(job_lead_params)
      respond_to do |format|
        format.html { redirect_to job_source_path(@job_source), notice: t('.notice') }
        format.turbo_stream { flash.now[:notice] = t('.notice') }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @job_lead.destroy

    respond_to do |format|
      format.html { redirect_to job_source_path(@job_source), notice: t('.notice') }
      format.turbo_stream { flash.now[:notice] = t('.notice') }
    end
  end

  private

  def job_lead_params
    params.require(:job_lead).permit(:title, :description, :link, :potential, :status, :owner_country, :hourly_rate, :published_at)
  end

  def set_job_source
    @job_source = current_user.job_sources.find(params[:job_source_id])
  end

  def set_job_lead
    @job_lead = @job_source.job_leads.find(params[:id])
  end

  def set_status_filter
    @status_filter = params['status_filter'] || params.dig('job_lead', 'status_filter')
    return unless @status_filter.present? && JobLead.statuses.keys.exclude?(@status_filter)

    raise ActionController::ActionControllerError, 'invalid value for :status_filter parameter'
  end

  def verify_sources_present
    return if current_user.job_sources.present?

    redirect_to job_sources_path and yield
  end
end

app/views/job_leads/_form.html.erb
<%= simple_form_for [job_source, job_lead] do |f| %>
  <%= form_server_error_notification(job_lead) %>
  <%= f.input :status_filter, as: :hidden, input_html: { value: @status_filter } %>

  <%= f.input :title, wrapper_html: { class: 'form__group-vertical' } %>

  <%= f.input :description, input_html: { rows: 5 }, wrapper_html: { class: 'form__group-vertical' } %>

  <%= f.input :link, as: :string, wrapper_html: { class: 'form__group-vertical' } %>

  <div class="form__row">
    <%= f.input :hourly_rate %>

    <%= f.input :owner_country, collection: ISO3166::Country.all_names_with_codes, selected: job_lead.owner_country %>
  </div>

  <div class="form__row">
    <%= f.input :status, collection: JobLead.statuses.keys, selected: job_lead.status %>

    <%= f.input :potential, collection: JobLead.potentials.keys, selected: job_lead.potential %>

    <%= f.input :published_at, html5: true %>
  </div>

  <div class="form__actions">
    <%= link_to "Cancel", job_source_path(job_source), class: "btn btn--light" %>
    <%= f.submit class: "btn btn--secondary" %>
  </div>  
<% end %>

app/views/job_leads/_job_lead.html.erb
<%= turbo_frame_tag job_lead do %>
  <div class="job-lead-list-item">
    <div class="ribbon">
      <span class="ribbon__title" data-status="<%= job_lead.status %>">
        <%= job_lead.status %>
    </div>
    <%= render partial: 'job_leads/job_lead_body', locals: { job_lead: job_lead } %>
  </div>
<% end %>  

app/views/job_leads/_job_lead_body.html.erb
<div class="job-lead-list-item__body">
  <div class="dropdown">
    <div class="dropdown__button">
      <i class="fas fa-solid fa-bars fa-xl"></i>
    </div>

    <ul class="dropdown__options">
      <li>
        <%= confirmation_link_to "Open Link",
                                 job_lead.link,
                                 target: '_blank',
                                 data: { message: "Open #{job_lead.link} ?" } %>
      </li>
      <li>
        <%= link_to "Job Source", job_source_path(job_lead.job_source), data: { turbo_frame: "_top" } %>
      </li>
      <% if job_lead.active_status? || job_lead.entry_status? %>
        <li>
          <%= confirmation_link_to "Detach",
                                   job_source_job_lead_path(job_lead.job_source, job_lead, status_filter: @status_filter, job_lead: { status: 'detached' }),
                                   data: { turbo_method: :patch, message: "Not interested? Are you sure?" } %>
        </li>
      <% end %>
      <% if job_lead.detached_status? || job_lead.entry_status? %>
        <li>
          <%= confirmation_link_to "Go Ahead",
                                   job_source_job_lead_path(job_lead.job_source, job_lead, status_filter: @status_filter, job_lead: { status: 'active' }),
                                   data: { turbo_method: :patch, message: "Do you want to begin to consider?" } %>
        </li>
      <% end %>
      <li>
        <%= link_to "Show", job_lead_path(job_lead, status_filter: @status_filter), data: { turbo_frame: "_top" } %>    
      </li>
      <li>
        <%= link_to "Edit", edit_job_source_job_lead_path(job_lead.job_source, job_lead, status_filter: @status_filter) %>    
      </li>
      <li>
        <%= confirmation_link_to "Delete",
                                 job_source_job_lead_path(job_lead.job_source, job_lead),
                                 data: { turbo_method: :delete, message: "DELETE? Are you sure?" } %>
      </li>
    </ul>
  </div>
  <div class="job-lead-list-item__name">
    <div class="job-lead-list-item__hourly-rate">
      <%= number_to_currency job_lead.hourly_rate %>
    </div>
    <div class="job-lead-list-item__title">
      <%= job_lead.formatted_title %>
    </div>
  </div>  
  <div class="job-lead-list-item__description">
    <%= strip_tags(job_lead.description).truncate(250, separator: /\s/, ommission: "....") %>
  </div>
  <div class="job-lead-list-item__info">
    <div class="job-lead-list-item__source-name">
      <%= job_lead.job_source.name %>
    </div>
    <div class="job-lead-list-item__published-at">
      <%= time_ago_in_words job_lead.published_at %> ago
    </div>
  </div>
</div>

app/views/job_leads/create.turbo_stream.erb
<%= turbo_stream.update JobLead.new, "" %>

<% if next_lead = @job_lead.next_lead_by_status %>
  <%= turbo_stream.after next_lead do %>
    <%= render @job_lead, job_source: @job_source %>
  <% end %>

<% else %>

  <%= turbo_stream.prepend "job_source_leads" do %>
    <%= render @job_lead, job_source: @job_source %>
  <% end %>

  <%= turbo_stream.prepend "job_leads" do %>
    <%= render @job_lead %>
  <% end %>

<% end %>

<%= render_turbo_stream_flash_messages %>

app/views/job_leads/destroy.turbo_stream.erb
<%= turbo_stream.remove @job_lead %>
<%= render_turbo_stream_flash_messages %>

app/views/job_leads/edit.html.erb
<%= link_to sanitize("&larr; Back to Job Source"), job_source_path(@job_source) %>

<div class="header">
  <h2>Edit Job Lead</h2>
</div>

<%= turbo_frame_tag @job_lead do %>
  <%= render "form", job_source: @job_source, job_lead: @job_lead %>
<% end %>  

app/views/job_leads/index.html.erb
<%= turbo_stream_from current_user, "job_leads" %>

<div class="header">
  <h2>Job Leads</h2>
</div>

<% if @status_filter.blank? && @job_leads.blank? %>
  <div class="empty-state">
    <p class="empty-state__text">
      You don't have any leads yet.<br />
      Please go to Job Sources page and add leads there<br />
      or customize the source for auto SYNC leads to your feed. 
    </p>
    <%= link_to "Go to Job Sources", job_sources_path, class: "btn btn--primary" %>
  </div>
<% else %>
  <div class="horizontal-filter">
    <%= link_to "All",
                job_leads_path,
                class: "horizontal-filter__item#{ @status_filter ? '' : ' active' }" %>
    <% JobLead.statuses.keys.each do |status| %>
      <%= link_to status.capitalize,
                  job_leads_path(status_filter: status),
                  class: "horizontal-filter__item#{ @status_filter == status ? ' active' : '' }" %>
    <% end %>
  </div>

  <% if @job_leads.blank? %>
    <div class="empty-state">
      <p class="empty-state__text">
        You don't have any leads in <%= @status_filter.capitalize %> status
      </p>
    </div>
  <% else %>
    <% turbo_stream_name = @status_filter ? "job_leads-status-#{@status_filter}" : "job_leads" %>
    <%= turbo_frame_tag turbo_stream_name do %>
      <%= render @job_leads %>
    <% end %>
  <% end %>
<% end %>

app/views/job_leads/new.html.erb
<%= link_to sanitize("&larr; Back to Job Source"), job_source_path(@job_source) %>

<div class="header">
  <h2>New Job Lead</h2>
</div>

<%= turbo_frame_tag @job_lead do %>
  <%= render "form", job_source: @job_source, job_lead: @job_lead %>
<% end %>

app/views/job_leads/show.html.erb
<%= link_to sanitize("&larr; Back to job leads"), job_leads_path(status_filter: @status_filter) %>

<div class="header">
  <h2>
    Job Lead from <%= link_to @job_lead.job_source.name,
                              job_source_path(@job_lead.job_source),
                              data: { turbo_frame: "_top" } %>
  </h2>
</div>

<div class="job-lead-container">
  <div class="job-lead-container__body">
    <div class="job-lead-container__body-title-and-description">
      <div class="job-lead-container__body-title">
        <%= @job_lead.formatted_title %>
        <%= confirmation_link_to @job_lead.link,
                                 target: '_blank',
                                 data: { turbo_method: :patch, message: "Open #{@job_lead.link} ?" } do %>
          <i class="fas fa-solid fa-arrow-up-right-from-square fa-xl"></i>
        <% end %>  
      </div>
      <div class="job-lead-container__body-description">
        <%= collapsible(visible_height_rem: 10.5) do %>
          <%= @job_lead.sanitized_description %>
        <% end %>
      </div>
    </div>
    <div class="job-lead-container__body-attributes">
      <div class="job-lead-container__body-attribute">
        <div class="job-lead-container__body-attribute-value">
          $<%= @job_lead.hourly_rate %>/h
        </div>
        <div class="job-lead-container__body-attribute-label">
          Rate
        </div>
      </div>
      <div class="job-lead-container__body-attribute">
        <div class="job-lead-container__body-attribute-value">
          <%= @job_lead.status.capitalize %>
        </div>
        <div class="job-lead-container__body-attribute-label">
          Status
        </div>
      </div>
      <div class="job-lead-container__body-attribute">
        <div class="job-lead-container__body-attribute-value">
          <%= @job_lead.potential.capitalize %>
        </div>
        <div class="job-lead-container__body-attribute-label">
          Potential
        </div>
      </div>

      <div class="job-lead-container__body-attribute">
        <div class="job-lead-container__body-attribute-value">
          <%= time_ago_in_words(@job_lead.published_at) %> ago
        </div>
        <div class="job-lead-container__body-attribute-label">
          <%= l(@job_lead.published_at, format: :specific_format) %>
        </div>
       </div>
    </div>
  </div>

  <div class="job-lead-container__actions">
    <%= link_to new_note_path(note: { owner_type: 'JobLead', owner_id: @job_lead.id }),
                data: { turbo_frame: dom_id(Note.new) },
                class: "btn btn--secondary" do %>
      <i class="fa-regular fa-note-sticky fa-lg"></i>
      <label>New Note</label>
    <% end %> 

    <% if @job_lead.detached_status? || @job_lead.entry_status? %>
      <%= confirmation_link_to job_source_job_lead_path(@job_lead.job_source, @job_lead, job_lead: { status: 'active' }),
                               class: "btn btn--secondary",
                               data: { turbo_method: :patch, message: "Do you want to begin to consider?" } do %>
        <i class="fa-solid fa-fire fa-lg"></i>
        <label>Go Ahead</label>
      <% end %>
    <% end %>

    <%= link_to [:edit, @job_lead.job_source, @job_lead],
                class: "btn btn--light" do %>
      <i class="fa-solid fa-pen-to-square fa-lg"></i>
      <label>Edit</label>
    <% end %>

    <% if @job_lead.active_status? || @job_lead.entry_status? %>
      <%= confirmation_link_to job_source_job_lead_path(@job_lead.job_source, @job_lead, job_lead: { status: 'detached' }),
                               class: "btn btn--primary",
                               data: { turbo_method: :patch, message: "Not interested? Are you sure?" } do %>
        <i class="fa-solid fa-ban fa-lg"></i>
        <label>Detach</label>
      <% end %>  
    <% end %>

    <%= confirmation_link_to job_source_job_lead_path(@job_lead.job_source, @job_lead),
                             class: "btn btn--primary",
                             data: { turbo_method: :delete, message: "DELETE? Are you sure?" } do %>
      <i class="fa-solid fa-trash fa-lg"></i>
      <label>Delete</label>
    <% end %>
  </div>

  <div class="job-lead-container__notes">
    <%= turbo_frame_tag Note.new %>

    <%= turbo_frame_tag "notes" do %>
      <%= render @job_lead.notes.ordered %>
    <% end %>
  </div>
</div>  

app/views/job_leads/update.turbo_stream.erb
<%= turbo_stream.remove @job_lead %>

<% next_lead = @job_lead.next_lead_by_status(@status_filter) %>
<% if next_lead && (@status_filter.blank? || @job_lead.status == @status_filter) %>
  <%= turbo_stream.after next_lead do %>
    <%= render @job_lead, job_source: @job_source %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "job_source_leads" do %>
    <%= render @job_lead, job_source: @job_source %>
  <% end %>

  <%= turbo_stream.prepend "job_leads" do %>
    <%= render @job_lead %>
  <% end %>

  <%= turbo_stream.prepend "job_leads-status-#{@job_lead.status}" do %>
    <%= render @job_lead %>
  <% end %>
<% end %>

<%= render_turbo_stream_flash_messages %>