config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    authenticate :user, ->(user) { user.is_admin? } do
      mount Sidekiq::Web, at: 'sidekiq'
      mount PgHero::Engine, at: 'pghero'
    end
  end

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'job_leads#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :assistant_configurations, except: %i[show create]
  resources :gmail_integrations, controller: 'assistant_configurations'

  resources :job_sources do
    resources :job_leads, except: %i[index show]
  end
  resources :job_leads, only: %i[index show]
  resources :notifiers, except: %i[index show] do
    member do
      patch :refresh_telegram_token
    end
  end
  resources :notes, only: %i[new create destroy]
  resources :gmail_messages, only: %i[index show]

  namespace :telegram, defaults: { format: :json } do
    post :message
  end
  namespace :google_oauth2 do
    namespace :gmail do
      get :auth
      get :callback
    end
  end
end

Rails.application.routes.default_url_options[:host] = Rails.application.credentials.host

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div 
    class="flash__message"
    data-controller="element"
    data-action="animationend->element#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar" data-controller="navbar">
  <%= link_to authenticated_root_path, class: "navbar__brand" do %>
    My Workflow Assistant
  <% end %>

  <ul class="navbar__menu" data-navbar-target="menu" data-action="click->navbar#menuClick">
    <%# to the cache this >> %>
      <%= turbo_frame_tag "configurations_associated_resources_links" do %>
        <%= links_for_associated_resources_of_configurations %>
      <% end %>  
    <%# to the cache this << %>
    <li class="navbar__menu-item">
      <%= link_to job_leads_path, class: "btn btn--light" do %>
        <i class="fas fa-solid fa-briefcase fa-lg"></i>
        Job Leads
      <% end %>
    </li>
    <li class="navbar__menu-item">
      <%= link_to assistant_configurations_path, class: "btn btn--light" do %>
        <i class="fas fa-solid fa-gear fa-lg"></i>
        Settings
      <% end %>
    </li>
  </ul>

  <button class="navbar__toggler" data-navbar-target="togglerButton" data-action="click->navbar#togglerClick">
    <span></span>
  </button>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Workflow Assistant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    </div>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Workflow Assistant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
                
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body style="background-color: var(--color-light-glint);">
    <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    </div>

    <main class="authentication">
      <div class="authentication__column-space-left">
        <div class="authentication__form-container">
          <%= yield %>
        </div>
      </div>
      
      <div class="authentication__column-space-right">
        <div class="authentication__brand-name">
          <div>My Workflow</div>
          <div>Assistant</div>
        </div>
        <div class="authentication__brand-slogan">leave your workflow's routine to automation and AI</div>
      </div>
    </main>
  </body>
</html>